name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Pages
      uses: actions/setup-pages@v1

    - name: Build and Deploy
      run: |
        mkdir output
        cp -r docs/* output/
        echo "username.github.io/repo-name" > output/CNAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
